name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main  # o il tuo branch di produzione

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FLOWER_0884CA703 }}
          action: "upload"
          app_location: "/"  # dove si trova index.html
